import FormField from '@/Common_Pages/components/ui/FormField'
import FormSection from '@/Role_Pages/coordinator/register-applicant/components/FormSection'
import type { SectionProps } from '@/Role_Pages/coordinator/register-applicant/types/register-applicant'

// Identity & contact details. A temporary password is generated by the server
// and emailed to the applicant after registration.
const IdentityContactSection = ({ values, errors, onChange, onBlur, nicReadOnly }: SectionProps) => (
  <FormSection number={2} title="Identity and contact" description="These details are used for identification, sign-in and notifications.">
    <div className="grid gap-5 lg:grid-cols-3">
      <FormField label={nicReadOnly ? 'NIC (cannot be changed)' : 'NIC *'} name="nic" value={values.nic} onChange={onChange} onBlur={onBlur} error={errors.nic} placeholder="e.g. 200012345678" autoComplete="off" preventAutofill readOnly={nicReadOnly} />
      <FormField label="Mobile number *" name="phone" type="tel" inputMode="numeric" prefix="+94" maxLength={9} value={values.phone} onChange={onChange} onBlur={onBlur} error={errors.phone} placeholder="e.g. 771234567" autoComplete="off" preventAutofill />
      <FormField label="Email *" name="email" type="email" value={values.email} onChange={onChange} onBlur={onBlur} error={errors.email} placeholder="e.g. name@gmail.com" autoComplete="off" preventAutofill />
    </div>

    <div className="flex items-start gap-3 rounded-lg border border-emerald-300/15 bg-emerald-300/[0.06] px-4 py-3">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300"><path d="M12 3 4 6v5c0 5 3.4 8.5 8 10 4.6-1.5 8-5 8-10V6l-8-3Z"/><path d="m9 12 2 2 4-4"/></svg>
      <p className="text-sm leading-relaxed text-emerald-50">The server generates a secure temporary password and emails it directly to the applicant.</p>
    </div>
  </FormSection>
)

export default IdentityContactSection
