import FormField from '@/Common_Pages/components/ui/FormField'
import FormSection from '@/Role_Pages/coordinator/register-applicant/components/FormSection'
import type { SectionProps } from '@/Role_Pages/coordinator/register-applicant/types/register-applicant'

// Identity & contact details. A temporary password is generated by the server
// and emailed to the applicant after registration.
const IdentityContactSection = ({ values, errors, onChange, onBlur, nicReadOnly }: SectionProps) => (
  <FormSection title="Identity & contact">
    <FormField label={nicReadOnly ? 'NIC (cannot be changed)' : 'NIC *'} name="nic" value={values.nic} onChange={onChange} onBlur={onBlur} error={errors.nic} placeholder="e.g. 200012345678" autoComplete="off" preventAutofill readOnly={nicReadOnly} />

    <div className="grid gap-4 sm:grid-cols-2">
      <FormField label="Mobile number *" name="phone" type="tel" inputMode="numeric" prefix="+94" maxLength={9} value={values.phone} onChange={onChange} onBlur={onBlur} error={errors.phone} placeholder="e.g. 771234567" autoComplete="off" preventAutofill />
      <FormField label="Email *" name="email" type="email" value={values.email} onChange={onChange} onBlur={onBlur} error={errors.email} placeholder="e.g. name@gmail.com" autoComplete="off" preventAutofill />
    </div>

    <p className="rounded-xl border border-gold-300/20 bg-gold-300/10 px-4 py-3 text-sm text-emerald-50/85">
      A secure temporary password will be generated automatically and sent to the applicant&apos;s email address.
    </p>
  </FormSection>
)

export default IdentityContactSection
